// lib/models/quiz_model.dart

import 'package:cloud_firestore/cloud_firestore.dart';

/// **Why we used this class (QuizModel):**
/// This class acts as the "blueprint" for a single Quiz in our application.
/// Just like a house needs a blueprint before construction, our app needs this model
/// to know exactly what a "Quiz" looks like (it has a title, duration, questions, etc.).
///
/// **How it helps:**
/// It ensures that whenever we handle quiz data (fetching from Firebase or saving it),
/// we always have the correct data types. It prevents bugs where we might accidentally
/// try to save a "text" duration instead of a "number".
class QuizModel {
  // **Data Fields:**
  // These variables hold the actual information for one specific quiz.

  final String
  quizId; // The unique ID generated by Firebase for this quiz document.

  // This is a "Foreign Key". It links this quiz to a specific Subject (e.g., "Math").
  // It allows us to find all quizzes that belong to "Math" easily.
  final String subjectId;

  final String title; // The name of the quiz (e.g., "Algebra Basics").
  final String
  createdBy; // The User ID (UID) of the teacher who created this quiz.
  final Timestamp createdAt; // When this quiz was created (used for sorting).

  final int durationMin; // How long the quiz lasts (in minutes).
  final int
  totalQuestions; // The target number of questions this quiz should have.
  final int
  marksPerQuestion; // How many marks a student gets for one correct answer.

  // The state of the quiz.
  // 'draft': Only visible to the teacher (editing mode).
  // 'published': Visible to students (ready to take).
  final String status;

  // **Constructor:**
  // Creates a real instance of a QuizModel with all required data.
  QuizModel({
    required this.quizId,
    required this.subjectId,
    required this.title,
    required this.createdBy,
    required this.createdAt,
    required this.durationMin,
    required this.totalQuestions,
    required this.marksPerQuestion,
    required this.status,
  });

  /// **What is this Factory Constructor? (empty)**
  /// This creates a "blank" or "default" quiz object.
  ///
  /// **Why do we need it?**
  /// Sometimes (like when first opening a creation form), we need a placeholder object
  /// that isn't null but doesn't have real data yet. This prevents "Null Pointer Exceptions".
  factory QuizModel.empty() {
    return QuizModel(
      quizId: '',
      subjectId: '',
      title: '',
      createdBy: '',
      createdAt: Timestamp.now(),
      durationMin: 25, // Default duration is set to 25 minutes.
      totalQuestions: 25, // Default question count target is 25.
      marksPerQuestion: 1, // Default marks per question is 1.
      status:
          'draft', // New quizzes always start as drafts to prevent accidental publishing.
    );
  }

  /// **What is this Factory Constructor? (fromFirestore)**
  /// This converts the raw data we get from the Firebase Database (DocumentSnapshot)
  /// into a nice, usable `QuizModel` object.
  ///
  /// **How it works:**
  /// 1. It extracts the `data()` map from the document.
  /// 2. It reads each field (like 'title') and assigns it to our class variables.
  /// 3. It uses `??` (null check) to provide safe default values if a field is missing in the database.
  factory QuizModel.fromFirestore(DocumentSnapshot doc) {
    // Cast the document data to a Map<String, dynamic> safely.
    Map<String, dynamic> data = doc.data() as Map<String, dynamic>? ?? {};

    return QuizModel(
      // The ID is not inside the data map, it's the name of the document itself.
      quizId: doc.id,

      subjectId: data['subjectId'] ?? '',
      title: data['title'] ?? '',
      createdBy: data['createdBy'] ?? '',

      // If 'createdAt' is missing, use the current time as a fallback.
      createdAt: data['createdAt'] ?? Timestamp.now(),

      durationMin: data['durationMin'] ?? 25,
      totalQuestions: data['totalQuestions'] ?? 25,
      marksPerQuestion: data['marksPerQuestion'] ?? 1,
      status: data['status'] ?? 'draft',
    );
  }

  /// **What is this method? (toMap)**
  /// This converts our Dart object *back* into a Map (JSON format).
  ///
  /// **Why do we need it?**
  /// Firebase doesn't understand Dart classes. To save or update data in the database,
  /// we must convert it into a standard key-value map.
  Map<String, dynamic> toMap() {
    return {
      // Note: We DO NOT save 'quizId' inside the map because the ID
      // is already the key (name) of the document in the database.
      'subjectId': subjectId,
      'title': title,
      'createdBy': createdBy,
      'createdAt': createdAt,
      'durationMin': durationMin,
      'totalQuestions': totalQuestions,
      'marksPerQuestion': marksPerQuestion,
      'status': status,
    };
  }
}
