// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDClhcovb2gXSy_CKPxQS37sJd2Li3me78',
    appId: '1:823498154753:web:c5be72c5108d90e6d63100',
    messagingSenderId: '823498154753',
    projectId: 'online-quiz-892aa',
    authDomain: 'online-quiz-892aa.firebaseapp.com',
    storageBucket: 'online-quiz-892aa.firebasestorage.app',
    measurementId: 'G-P9HRZ3Z759',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyjINf6ULf64Va9LJv0fu_oRKZZNxIXQ8',
    appId: '1:823498154753:android:eb255a8f5ce8af69d63100',
    messagingSenderId: '823498154753',
    projectId: 'online-quiz-892aa',
    storageBucket: 'online-quiz-892aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUWrG-lRys09sYW2gugOtxk9uRf7Po2y4',
    appId: '1:823498154753:ios:a37b14b20944e3a9d63100',
    messagingSenderId: '823498154753',
    projectId: 'online-quiz-892aa',
    storageBucket: 'online-quiz-892aa.firebasestorage.app',
    iosBundleId: 'com.example.quizPanel',
  );
}
